In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import warnings

# Suppress warnings
warnings.filterwarnings('ignore')

In [50]:
df = pd.read_csv('train.csv')
df

id  Marital status  Application mode  Application order  Course  \
0          0               1                 1                  1    9238   
1          1               1                17                  1    9238   
2          2               1                17                  2    9254   
3          3               1                 1                  3    9500   
4          4               1                 1                  2    9500   
...      ...             ...               ...                ...     ...   
76513  76513               1                17                  1    9254   
76514  76514               1                 1                  6    9254   
76515  76515               5                17                  1    9085   
76516  76516               1                 1                  3    9070   
76517  76517               1                 1                  1    9773   

       Daytime/evening attendance  Previous qualification  \
0                               1                       1   
1                               1                       1   
2                               1                       1   
3                               1                       1   
4                               1                       1   
...                           ...                     ...   
76513                           1                       1   
76514                           1                       1   
76515                           1                       1   
76516                           1                       1   
76517                           1                       1   

       Previous qualification (grade)  Nacionality  Mother's qualification  \
0                               126.0            1                       1   
1                               125.0            1                      19   
2                               137.0            1                       3   
3                               131.0            1                      19   
4                               132.0            1                      19   
...                               ...          ...                     ...   
76513                           121.0            1                      19   
76514                           125.0            1                       1   
76515                           138.0            1                      37   
76516                           136.0            1                      38   
76517                           133.1            1                      19   

       ...  Curricular units 2nd sem (credited)  \
0      ...                                    0   
1      ...                                    0   
2      ...                                    0   
3      ...                                    0   
4      ...                                    0   
...    ...                                  ...   
76513  ...                                    0   
76514  ...                                    0   
76515  ...                                    0   
76516  ...                                    0   
76517  ...                                    0   

       Curricular units 2nd sem (enrolled)  \
0                                        6   
1                                        6   
2                                        6   
3                                        8   
4                                        7   
...                                    ...   
76513                                    6   
76514                                    6   
76515                                    5   
76516                                    6   
76517                                    6   

       Curricular units 2nd sem (evaluations)  \
0                                           7   
1                                           9   
2                                           0   
3                                          11   
4   

In [51]:
X_test = pd.read_csv('test.csv')
X_test_id = X_test.id
X_test_id

0         76518
1         76519
2         76520
3         76521
4         76522
          ...  
51007    127525
51008    127526
51009    127527
51010    127528
51011    127529
Name: id, Length: 51012, dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76518 entries, 0 to 76517
Data columns (total 38 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   id                                              76518 non-null  int64  
 1   Marital status                                  76518 non-null  int64  
 2   Application mode                                76518 non-null  int64  
 3   Application order                               76518 non-null  int64  
 4   Course                                          76518 non-null  int64  
 5   Daytime/evening attendance                      76518 non-null  int64  
 6   Previous qualification                          76518 non-null  int64  
 7   Previous qualification (grade)                  76518 non-null  float64
 8   Nacionality                                     76518 non-null  int64  
 9   Mother's qualification                 

In [53]:
df.describe(include='all')

id  Marital status  Application mode  Application order  \
count   76518.000000    76518.000000      76518.000000       76518.000000   
unique           NaN             NaN               NaN                NaN   
top              NaN             NaN               NaN                NaN   
freq             NaN             NaN               NaN                NaN   
mean    38258.500000        1.111934         16.054419           1.644410   
std     22088.988286        0.441669         16.682337           1.229645   
min         0.000000        1.000000          1.000000           0.000000   
25%     19129.250000        1.000000          1.000000           1.000000   
50%     38258.500000        1.000000         17.000000           1.000000   
75%     57387.750000        1.000000         39.000000           2.000000   
max     76517.000000        6.000000         53.000000           9.000000   

              Course  Daytime/evening attendance  Previous qualification  \
count   76518.000000                76518.000000            76518.000000   
unique           NaN                         NaN                     NaN   
top              NaN                         NaN                     NaN   
freq             NaN                         NaN                     NaN   
mean     9001.286377                    0.915314                3.658760   
std      1803.438531                    0.278416                8.623774   
min        33.000000                    0.000000                1.000000   
25%      9119.000000                    1.000000                1.000000   
50%      9254.000000                    1.000000                1.000000   
75%      9670.000000                    1.000000                1.000000   
max      9991.000000                    1.000000               43.000000   

        Previous qualification (grade)   Nacionality  Mother's qualification  \
count                     76518.000000  76518.000000            76518.000000   
unique                             NaN           NaN                     NaN   
top                                NaN           NaN                     NaN   
freq                               NaN           NaN                     NaN   
mean                        132.378766      1.226600               19.837633   
std                          10.995328      3.392183               15.399456   
min                          95.000000      1.000000                1.000000   
25%                         125.000000      1.000000                1.000000   
50%                         133.100000      1.000000               19.000000   
75%                         140.000000      1.000000               37.000000   
max                         190.000000    109.000000               44.000000   

        ...  Curricular units 2nd sem (credited)  \
count   ...                         76518.000000   
unique  ...                                  NaN   
top     ...                                  NaN   
freq    ...                                  NaN   
mean    ...                             0.137053   
std     ...                             0.933830   
min     ...                             0.000000   
25%     ...                             0.000000   
50%     ...                             0.000000   
75%     ...                             0.000000   
max     ...                            19.000000   

        Curricular units 2nd sem (enrolled)  \
count                          76518.000000   
unique                                  NaN   
top                                     NaN   
freq                                    NaN   
mean                               5.933414   
std                                1.627182   
min                                0.000000   
25%                                5.000000   
50%                                6.000000   
75%                                6.000000   
max                               23.000000   

        Curricular units 2nd 

In [54]:
df=df.drop('id',axis=1)
X_test=X_test.drop('id',axis=1)

In [55]:
df.isnull().sum().sum()

0

In [56]:
X_test.isnull().sum().sum()

0

In [57]:
df.Course.value_counts()

9500    12074
9773     8214
9238     7935
9147     7741
9254     5425
9085     5373
9670     4760
9991     4057
9003     3733
9070     3281
9853     3198
9119     3004
171      2859
8014     2438
9130     1606
9556      746
33         72
979         1
39          1
Name: Course, dtype: int64

in first calculation we are taking Course as numerical feature

In [58]:
# numerical_columns = df.drop('Course',axis=1)
# categorical_columns = df.Course

In [59]:

# df = pd.get_dummies(df, columns=['Course'], drop_first=True)

In [60]:
# X_test = pd.get_dummies(X_test, columns=['Course'], drop_first=True)

In [61]:
df.Target.value_counts()

Graduate    36282
Dropout     25296
Enrolled    14940
Name: Target, dtype: int64

In [62]:
X= df.drop('Target',axis = 1)
y = df.Target

In [63]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_test = scaler.transform(X_test)
# Convert the scaled array back to a DataFrame
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)
X_train = X_scaled.copy() # tire 2 code
y_train = y.copy() #tire 2 code
# Split data into train, test, and cv sets
# X_test, X_cv, y_test, y_cv = train_test_split(X_cv, y_cv, test_size=0.5, random_state=42, stratify=y_temp)

In [64]:
X_train, X_cv, y_train, y_cv = train_test_split(X_train, y_train, test_size=0.2, random_state=42, stratify=y_train) #tire 2 code removal


In [65]:
aa

NameError: name 'aa' is not defined

In [66]:
# y.value_counts()

In [67]:
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")
from tqdm import tqdm

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

In [18]:



# Parameter grids for hyperparameter tuning
param_grids = {
    DecisionTreeClassifier: {'max_depth': [3, 5, 10], 'min_samples_split': [2, 5, 10]},
    RandomForestClassifier: {'n_estimators': [50, 100, 200], 'max_depth': [3, 5, 10]},
    GradientBoostingClassifier: {'n_estimators': [50, 100, 200], 'learning_rate': [0.01, 0.1, 0.2]},
    AdaBoostClassifier: {'n_estimators': [50, 100, 200], 'learning_rate': [0.01, 0.1, 0.2]},
    SVC: {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']},
    NuSVC: {'nu': [0.1, 0.5, 0.9], 'kernel': ['linear', 'rbf']},
    LogisticRegression: {'C': [0.1, 1, 10]},
    SGDClassifier: {'alpha': [0.0001, 0.001, 0.01], 'max_iter': [1000, 1500]},
    KNeighborsClassifier: {'n_neighbors': [3, 5, 10]},
    GaussianNB: {},
    MultinomialNB: {'alpha': [0.1, 0.5, 1.0]},
    LinearDiscriminantAnalysis: {'solver': ['svd', 'lsqr', 'eigen']},
    QuadraticDiscriminantAnalysis: {'reg_param': [0.0, 0.1, 0.5]},
    XGBClassifier: {'n_estimators': [50, 100, 200], 'learning_rate': [0.01, 0.1, 0.2]},
}

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
    GaussianNB(),
    MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),
]

# Loop through each algorithm
for clf in classifiers:
    clf_name = clf.__class__
    param_grid = param_grids[clf_name]
    grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)
    best_clf = grid_search.best_estimator_
    y_pred = best_clf.predict(X_cv)
    accuracy = accuracy_score(y_cv, y_pred)
    cm = confusion_matrix(y_cv, y_pred)
    print(f"{clf_name.__name__}: Best Params - {grid_search.best_params_}, Accuracy - {accuracy}, Confusion Matrix -\n{cm}")


DecisionTreeClassifier: Best Params - {'max_depth': 5, 'min_samples_split': 2}, Accuracy - 0.8097882906429692, Confusion Matrix -
[[4084  570  405]
 [ 385 1654  949]
 [  88  514 6655]]
RandomForestClassifier: Best Params - {'max_depth': 10, 'n_estimators': 200}, Accuracy - 0.8223993727130162, Confusion Matrix -
[[4094  595  370]
 [ 298 1767  923]
 [ 130  402 6725]]
GradientBoostingClassifier: Best Params - {'learning_rate': 0.2, 'n_estimators': 200}, Accuracy - 0.8295870360690015, Confusion Matrix -
[[4192  531  336]
 [ 368 1809  811]
 [ 128  434 6695]]
AdaBoostClassifier: Best Params - {'learning_rate': 0.2, 'n_estimators': 200}, Accuracy - 0.8205697856769472, Confusion Matrix -
[[4169  526  364]
 [ 378 1709  901]
 [ 144  433 6680]]
SVC: Best Params - {'C': 10, 'kernel': 'rbf'}, Accuracy - 0.8171719811813904, Confusion Matrix -
[[4011  682  366]
 [ 290 1730  968]
 [ 111  381 6765]]
NuSVC: Best Params - {'kernel': 'rbf', 'nu': 0.5}, Accuracy - 0.7978959749085206, Confusion Matrix -
[[3

/Users/prayer/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/prayer/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

LogisticRegression: Best Params - {'C': 10}, Accuracy - 0.8153423941453215, Confusion Matrix -
[[4125  588  346]
 [ 358 1642  988]
 [ 154  392 6711]]
SGDClassifier: Best Params - {'alpha': 0.0001, 'max_iter': 1000}, Accuracy - 0.7970465237846315, Confusion Matrix -
[[4124  497  438]
 [ 462 1167 1359]
 [ 178  172 6907]]
KNeighborsClassifier: Best Params - {'n_neighbors': 10}, Accuracy - 0.7746994249869316, Confusion Matrix -
[[4010  582  467]
 [ 413 1363 1212]
 [ 168  606 6483]]
GaussianNB: Best Params - {}, Accuracy - 0.761565603763722, Confusion Matrix -
[[3978  630  451]
 [ 355 1255 1378]
 [ 288  547 6422]]
MultinomialNB: Best Params - {'alpha': 1.0}, Accuracy - 0.7007318348144276, Confusion Matrix -
[[3849   32 1178]
 [ 648   86 2254]
 [ 405   63 6789]]
LinearDiscriminantAnalysis: Best Params - {'solver': 'svd'}, Accuracy - 0.802012545739676, Confusion Matrix -
[[3852  787  420]
 [ 205 1678 1105]
 [ 127  386 6744]]
QuadraticDiscriminantAnalysis: Best Params - {'reg_param': 0.0}, Acc

ValueError: 
All the 27 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/prayer/anaconda3/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/prayer/anaconda3/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/Users/prayer/anaconda3/lib/python3.10/site-packages/xgboost/sklearn.py", line 1467, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['Dropout' 'Enrolled' 'Graduate']


<!-- R² score: 0.9685924036661305
Best parameters: {'max_depth': 10, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 300} -->

In [ ]:
# y_pred = model.predict(X_test)
# y_pred = np.round(y_pred).astype(int)
# y_pred

Final Model

In [69]:
model = RandomForestClassifier(max_depth= 10, max_features='auto', min_samples_leaf=4, min_samples_split=2, n_estimators=300)
model.fit(X_scaled, y)

RandomForestClassifier(max_depth=10, max_features='auto', min_samples_leaf=4,
                       n_estimators=300)

In [70]:
y_pred = model.predict(X_test)


In [71]:
y_pred

array(['Dropout', 'Graduate', 'Graduate', ..., 'Dropout', 'Dropout',
       'Dropout'], dtype=object)

In [72]:
submission = pd.DataFrame()
submission['id'] = X_test_id
submission['Target'] = y_pred
submission

id    Target
0       76518   Dropout
1       76519  Graduate
2       76520  Graduate
3       76521  Graduate
4       76522  Enrolled
...       ...       ...
51007  127525   Dropout
51008  127526   Dropout
51009  127527   Dropout
51010  127528   Dropout
51011  127529   Dropout

[51012 rows x 2 columns]

In [73]:
submission.to_csv('submission.csv', index=False)